#!/bin/bash
# Last update: June 23th, 2021
# Author aaPanel Jose
## Start installation
yum install -y wget && wget -O install.sh http://www.aapanel.com/script/install_6.0_en.sh && echo y|bash install.sh aapanel
